"""
2026年5月热门AI工具补充脚本
对比现有tools.json，找出真正缺失的工具并写入基础数据
"""
import json, re, os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOLS_JSON_PATH = os.path.join(BASE_DIR, 'data', 'tools.json')

# 2026年5月真正热门但尚未入库的AI工具（严格去重后）
# 每个工具包含必需字段，content用占位符后续由API补充
NEW_TOOLS = [
    {
        "name": "OpenHands",
        "slug": "openhands",
        "emoji": "🤲",
        "color": "#4A90D2",
        "description": "开源AI软件工程师平台，能理解自然语言指令并自主完成代码编辑、命令执行、浏览器操作等复杂任务，是Devin的开源替代方案。",
        "category": "AI编程",
        "tags": [{"text": "AI编程"}, {"text": "开源"}],
        "rating": "⭐ 4.4",
        "visits": "N/A",
        "badge": None,
        "url": "https://github.com/All-Hands-AI/OpenHands",
        "price": "开源免费",
        "platform": "Web / Self-hosted",
        "pros": ["开源免费", "功能全面", "社区活跃", "支持多模型"],
        "cons": ["部署复杂", "需要技术背景", "资源消耗大"],
        "features": ["代码编辑", "命令执行", "浏览器自动化", "文件操作"],
        "faq": [],
        "content": "OpenHands是2026年最受关注的开源AI编程助手之一...",
        "published": False,
    },
    {
        "name": "Amp",
        "slug": "amp",
        "emoji": "⚡",
        "color": "#FF6B35",
        "description": "由Multion团队推出的AI浏览器代理，能自主完成网页任务，包括购物、预订、信息收集等复杂操作。",
        "category": "AI自动化",
        "tags": [{"text": "AI代理"}, {"text": "浏览器自动化"}],
        "rating": "⭐ 4.3",
        "visits": "N/A",
        "badge": None,
        "url": "https://amp.multion.com",
        "price": "等待列表",
        "platform": "Web",
        "pros": ["自主能力强", "真实网页操作", "多步骤任务"],
        "cons": ["尚未公开", "仅限邀请", "稳定性未知"],
        "features": ["网页自动化", "多步骤任务", "真实浏览器操作"],
        "faq": [],
        "content": "Amp是2026年最受期待的AI浏览器代理之一...",
        "published": False,
    },
    {
        "name": "Cluely",
        "slug": "cluely",
        "emoji": "👁️",
        "color": "#6B46C1",
        "description": "实时AI辅助工具，在视频通话、面试、在线会议中提供实时答案和建议，引发广泛争议的同时快速获得大量用户。",
        "category": "AI效率",
        "tags": [{"text": "实时辅助"}, {"text": "争议产品"}],
        "rating": "⭐ 3.8",
        "visits": "N/A",
        "badge": None,
        "url": "https://cluely.com",
        "price": "免费+付费版",
        "platform": "Mac / Windows",
        "pros": ["实时响应", "多场景适用", "Easy to use"],
        "cons": ["伦理争议", "可能被禁止使用", "依赖网络"],
        "features": ["实时答案", "屏幕捕捉", "面试辅助"],
        "faq": [],
        "content": "Cluely是2026年最具争议的AI工具之一...",
        "published": False,
    },
    {
        "name": "Cerebras",
        "slug": "cerebras",
        "emoji": "🧠",
        "color": "#F7931E",
        "description": "基于晶圆级芯片（WSE）的AI推理平台，提供极速大模型推理服务，速度远超传统GPU方案，已被多个AI应用采用。",
        "category": "AI对话",
        "tags": [{"text": "AI推理"}, {"text": "硬件加速"}],
        "rating": "⭐ 4.6",
        "visits": "N/A",
        "badge": None,
        "url": "https://cerebras.ai",
        "price": "按量付费",
        "platform": "API / Web",
        "pros": ["速度极快", "大上下文", "企业级稳定"],
        "cons": ["成本高", "模型选择少", "API仅英文优化"],
        "features": ["极速推理", "超大上下文", "企业API"],
        "faq": [],
        "content": "Cerebras是2026年AI推理领域的技术突破者...",
        "published": False,
    },
    {
        "name": "OpenRouter",
        "slug": "openrouter",
        "emoji": "🔀",
        "color": "#10A37F",
        "description": "AI模型统一接入平台，通过一个API接口调用1700+个大语言模型，自动选择最优价格和性能的模型，是AI开发的必备工具。",
        "category": "AI编程",
        "tags": [{"text": "模型聚合"}, {"text": "开发者工具"}, {"text": "免费可用", "type": "free"}],
        "rating": "⭐ 4.7",
        "visits": "N/A",
        "badge": None,
        "url": "https://openrouter.ai",
        "price": "按量付费（很低价）",
        "platform": "API / Web",
        "pros": ["模型极多", "价格透明", "统一接口", "免费额度"],
        "cons": ["需要技术背景", "部分模型不稳定", "依赖第三方"],
        "features": ["1700+模型", "统一API", "价格对比", "流式响应"],
        "faq": [],
        "content": "OpenRouter是2026年AI开发者最常用的模型聚合平台...",
        "published": False,
    },
    {
        "name": "Mistral AI",
        "slug": "mistral-ai",
        "emoji": "🌪️",
        "color": "#FF7000",
        "description": "欧洲领先的开源AI公司，提供Mistral 7B、Mixtral 8x22B等高性能开源模型，以及Premium API服务，以效率和透明度著称。",
        "category": "AI对话",
        "tags": [{"text": "开源模型"}, {"text": "欧洲AI"}, {"text": "免费可用", "type": "free"}],
        "rating": "⭐ 4.5",
        "visits": "N/A",
        "badge": None,
        "url": "https://mistral.ai",
        "price": "免费版+Premium $7.5/百万token",
        "platform": "Web / API",
        "pros": ["开源透明", "性价比高", "欧洲数据合规", "多语言支持"],
        "cons": ["英文为主", "中文稍弱", "生态较OpenAI小"],
        "features": ["开源模型下载", "Le Chat对话", "API接入", "多模态支持"],
        "faq": [],
        "content": "Mistral AI是2026年欧洲最具影响力的AI公司...",
        "published": False,
    },
    {
        "name": "LlamaIndex",
        "slug": "llamaindex",
        "emoji": "🦙",
        "color": "#4B5563",
        "description": "专业的LLM数据框架，专注于RAG（检索增强生成）场景，提供数据连接器、索引结构和查询引擎，是构建知识密集型AI应用的核心工具。",
        "category": "AI编程",
        "tags": [{"text": "RAG框架"}, {"text": "开源"}],
        "rating": "⭐ 4.5",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.llamaindex.ai",
        "price": "开源免费",
        "platform": "Python / TS",
        "pros": ["RAG专业", "文档完善", "社区活跃", "多数据源"],
        "cons": ["学习曲线陡", "需要编程基础", "配置复杂"],
        "features": ["数据连接器", "索引结构", "查询引擎", "Agent工具"],
        "faq": [],
        "content": "LlamaIndex是2026年RAG应用开发的标准框架...",
        "published": False,
    },
    {
        "name": "Chroma",
        "slug": "chroma",
        "emoji": "🎨",
        "color": "#3B82F6",
        "description": "轻量级开源向量数据库，专为AI应用快速原型设计，嵌入检索速度快，API简洁，是LangChain和LlamaIndex的默认向量存储方案之一。",
        "category": "AI编程",
        "tags": [{"text": "向量数据库"}, {"text": "开源"}],
        "rating": "⭐ 4.3",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.trychroma.com",
        "price": "开源免费",
        "platform": "Python / JS",
        "pros": ["轻量易用", "开源免费", "LangChain集成好"],
        "cons": ["功能不如Pinecone全面", "大规模性能待验证", "云服务不稳定"],
        "features": ["向量存储", "嵌入检索", "多语言SDK", "内存模式"],
        "faq": [],
        "content": "Chroma是2026年最易上手的向量数据库...",
        "published": False,
    },
    {
        "name": "Weaviate",
        "slug": "weaviate",
        "emoji": "🕸️",
        "color": "#4F46E5",
        "description": "开源向量搜索引擎，支持多种向量索引和模块化设计，可无缝集成ML模型，提供云托管和自部署两种方案，适合生产级AI应用。",
        "category": "AI编程",
        "tags": [{"text": "向量数据库"}, {"text": "开源"}, {"text": "企业级"}],
        "rating": "⭐ 4.4",
        "visits": "N/A",
        "badge": None,
        "url": "https://weaviate.io",
        "price": "开源+云服务",
        "platform": "Docker / Cloud",
        "pros": ["模块化设计", "多模型支持", "生产就绪", "活跃社区"],
        "cons": ["部署复杂", "资源消耗大", "学习成本高"],
        "features": ["向量搜索", "混合检索", "模块化架构", "云托管"],
        "faq": [],
        "content": "Weaviate是2026年企业级向量搜索的主流选择...",
        "published": False,
    },
    {
        "name": "CodeRabbit",
        "slug": "coderabbit",
        "emoji": "🐇",
        "color": "#FF6B6B",
        "description": "AI代码审查助手，自动分析GitHub/GitLab的Pull Request，提供行级评论、bug检测、性能建议和最佳实践提示，显著提升代码审查效率。",
        "category": "AI编程",
        "tags": [{"text": "代码审查"}, {"text": "GitHub集成"}],
        "rating": "⭐ 4.6",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.coderabbit.ai",
        "price": "免费版+Team $10/月",
        "platform": "GitHub / GitLab",
        "pros": ["审查质量高", "无缝集成", "学习团队规范", "免费版慷慨"],
        "cons": ["仅支持GitHub/GitLab", "有时误报", "需要PR触发"],
        "features": ["PR自动审查", "行级评论", "最佳实践提示", "学习团队规范"],
        "faq": [],
        "content": "CodeRabbit是2026年最受欢迎的AI代码审查工具...",
        "published": False,
    },
    {
        "name": "Mem",
        "slug": "mem-ai",
        "emoji": "🧠",
        "color": "#8B5CF6",
        "description": "AI驱动的笔记和知识管理工具，自动连接想法、笔记和内容，构建个人知识图谱，帮助用户发现意想不到的知识关联。",
        "category": "AI办公",
        "tags": [{"text": "知识管理"}, {"text": "AI笔记"}],
        "rating": "⭐ 4.2",
        "visits": "N/A",
        "badge": None,
        "url": "https://mem.ai",
        "price": "免费版+$10/月",
        "platform": "Web / iOS / Android",
        "pros": ["自动关联", "知识图谱", "多平台同步"],
        "cons": ["价格偏高", "学习成本高", "中文支持一般"],
        "features": ["AI自动关联", "知识图谱", "全文搜索", "多设备同步"],
        "faq": [],
        "content": "Mem是2026年AI知识管理领域的创新产品...",
        "published": False,
    },
    {
        "name": "Recall",
        "slug": "recall-ai",
        "emoji": "🧠",
        "color": "#059669",
        "description": "AI知识提取和记忆工具，自动总结网页、视频、播客内容，并建立知识网络，帮助高效积累和回顾信息。",
        "category": "AI效率",
        "tags": [{"text": "知识提取"}, {"text": "记忆增强"}],
        "rating": "⭐ 4.3",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.getrecall.ai",
        "price": "免费版+$8/月",
        "platform": "Web / Chrome扩展",
        "pros": ["自动总结", "知识网络", "多内容类型"],
        "cons": ["依赖Chrome", "付费功能多", "数据隐私顾虑"],
        "features": ["网页总结", "视频摘要", "知识网络", "智能搜索"],
        "faq": [],
        "content": "Recall是2026年知识工作者必备的AI记忆增强工具...",
        "published": False,
    },
    {
        "name": "KapKap",
        "slug": "kapkap",
        "emoji": "🎬",
        "color": "#EF4444",
        "description": "AI驱动的视频剪辑工具，专注于将长视频自动剪辑成短视频片段，智能识别高光时刻，一键生成适合TikTok/Reels/Shorts的短视频。",
        "category": "AI视频",
        "tags": [{"text": "视频剪辑"}, {"text": "短视频生成"}],
        "rating": "⭐ 4.4",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.kapkap.com",
        "price": "免费版+Pro $15/月",
        "platform": "Web / iOS / Android",
        "pros": ["智能剪辑", "多平台输出", "操作简单"],
        "cons": ["精度有限", "付费版功能多", "仅英文界面"],
        "features": ["AI高光识别", "自动剪辑", "多平台适配", "字幕生成"],
        "faq": [],
        "content": "KapKap是2026年短视频创作者的得力助手...",
        "published": False,
    },
    {
        "name": "Vizard",
        "slug": "vizard",
        "emoji": "🎯",
        "color": "#7C3AED",
        "description": "AI视频内容分析和剪辑平台，自动将长视频分割为多个短视频片段，内置AI虚拟主播功能，适合内容创作者批量生产社媒视频。",
        "category": "AI视频",
        "tags": [{"text": "视频剪辑"}, {"text": "虚拟主播"}],
        "rating": "⭐ 4.3",
        "visits": "N/A",
        "badge": None,
        "url": "https://vizard.ai",
        "price": "免费版+Pro $20/月",
        "platform": "Web",
        "pros": ["批量处理", "AI虚拟主播", "多语言支持"],
        "cons": ["剪辑精度有限", "付费墙明显", "输出质量一般"],
        "features": ["长视频分割", "AI虚拟主播", "自动字幕", "多平台输出"],
        "faq": [],
        "content": "Vizard是2026年适合批量视频内容生产的AI工具...",
        "published": False,
    },
    {
        "name": "Respeecher",
        "slug": "respeecher",
        "emoji": "🎙️",
        "color": "#1F2937",
        "description": "专业级AI语音克隆和配音平台，使用情感保留技术生成高度自然的语音复制品，被好莱坞电影和顶级播客采用。",
        "category": "AI音频",
        "tags": [{"text": "语音克隆"}, {"text": "专业级"}],
        "rating": "⭐ 4.7",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.respeecher.com",
        "price": "企业定制",
        "platform": "Web",
        "pros": ["语音质量极高", "情感保留", "好莱坞采用"],
        "cons": ["价格昂贵", "需要授权", "仅限企业"],
        "features": ["语音克隆", "情感保留", "多语言", "企业API"],
        "faq": [],
        "content": "Respeecher是2026年专业级AI语音克隆的标杆...",
        "published": False,
    },
    {
        "name": "StepFun Step-2",
        "slug": "stepfun-step2",
        "emoji": "🚶",
        "color": "#F59E0B",
        "description": "阶跃星辰推出的新一代多模态大模型，在数学推理、代码生成、中文理解等方面表现突出，是国产大模型的重要选手。",
        "category": "AI对话",
        "tags": [{"text": "国产大模型"}, {"text": "多模态"}],
        "rating": "⭐ 4.4",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.stepfun.com",
        "price": "免费版+API按量付费",
        "platform": "Web / API",
        "pros": ["中文能力强", "多模态支持", "推理能力突出"],
        "cons": ["国际知名度低", "API文档偏中文", "社区较小"],
        "features": ["多模态理解", "数学推理", "代码生成", "中文优化"],
        "faq": [],
        "content": "StepFun Step-2是2026年国产大模型的重要力量...",
        "published": False,
    },
    {
        "name": "Meticulous",
        "slug": "meticulous",
        "emoji": "🔬",
        "color": "#0891B2",
        "description": "AI驱动的UI测试自动化工具，自动记录用户操作并生成测试代码，无需手写测试脚本，大幅提升前端测试效率。",
        "category": "AI编程",
        "tags": [{"text": "自动化测试"}, {"text": "UI测试"}],
        "rating": "⭐ 4.5",
        "visits": "N/A",
        "badge": None,
        "url": "https://meticulous.ai",
        "price": "免费版+$25/月",
        "platform": "Web / CI集成",
        "pros": ["无需写测试代码", "自动更新快照", "CI集成好"],
        "cons": ["仅限前端测试", "学习配置成本", "依赖录制精度"],
        "features": ["自动生成测试", "快照更新", "CI/CD集成", "零代码维护"],
        "faq": [],
        "content": "Meticulous是2026年前端自动化测试的创新工具...",
        "published": False,
    },
    {
        "name": "Jasper Chat",
        "slug": "jasper-chat",
        "emoji": "🤖",
        "color": "#FF6B35",
        "description": "Jasper AI推出的对话式AI写作助手，专注于营销文案、品牌声音保持和SEO优化内容生成，是营销团队的内容生产利器。",
        "category": "AI写作",
        "tags": [{"text": "AI写作"}, {"text": "营销文案"}],
        "rating": "⭐ 4.3",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.jasper.ai/chat",
        "price": "$39/月起",
        "platform": "Web",
        "pros": ["品牌声音一致", "SEO优化", "多语言支持"],
        "cons": ["价格较高", "创意有限", "依赖Jasper生态"],
        "features": ["对话式写作", "品牌语调保持", "SEO模式", "多语言生成"],
        "faq": [],
        "content": "Jasper Chat是2026年营销团队最信赖的AI写作助手...",
        "published": False,
    },
    {
        "name": "Hippocratic AI",
        "slug": "hippocratic-ai",
        "emoji": "🏥",
        "color": "#DC2626",
        "description": "专注医疗健康领域的AI助手，提供症状分析、用药咨询、健康建议等服务，强调安全性和合规性，正在申请医疗AI认证。",
        "category": "AI效率",
        "tags": [{"text": "医疗AI"}, {"text": "健康咨询"}],
        "rating": "⭐ 4.2",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.hippocraticai.com",
        "price": "企业定制",
        "platform": "Web",
        "pros": ["医疗专业", "安全合规", "循证医学"],
        "cons": ["尚未全面开放", "仅限医疗场景", "需要专业审核"],
        "features": ["症状分析", "用药咨询", "健康建议", "循证内容"],
        "faq": [],
        "content": "Hippocratic AI是2026年医疗AI领域最受关注的创业公司...",
        "published": False,
    },
    {
        "name": "Ironclad AI",
        "slug": "ironclad-ai",
        "emoji": "📜",
        "color": "#1E40AF",
        "description": "AI驱动的合同管理和法律审查平台，自动识别合同条款风险、提取关键信息、生成合同摘要，大幅提升法务工作效率。",
        "category": "AI效率",
        "tags": [{"text": "法律AI"}, {"text": "合同管理"}],
        "rating": "⭐ 4.5",
        "visits": "N/A",
        "badge": None,
        "url": "https://www.ironclad.ai",
        "price": "企业定制",
        "platform": "Web",
        "pros": ["合同分析准确", "节省法务时间", "集成电子签名"],
        "cons": ["价格昂贵", "仅限企业", "需要培训"],
        "features": ["合同风险识别", "条款提取", "AI摘要", "电子签名集成"],
        "faq": [],
        "content": "Ironclad AI是2026年合同AI管理领域的领导者...",
        "published": False,
    },
]

def normalize_name(name):
    n = name.lower().strip()
    n = re.sub(r'\s+(AI|V\d+|ML|Pro|3D|\.com)\s*$', '', n)
    n = re.sub(r'（.*?）', '', n)
    return n.strip()

def is_duplicate(new_name, existing_tools):
    new_norm = normalize_name(new_name)
    for t in existing_tools:
        existing_norm = normalize_name(t["name"])
        if new_norm == existing_norm:
            return True, f"同名: {t['name']}"
        if t["slug"].lower() == normalize_name(new_name).replace(' ', '-'):
            return True, f"slug冲突: {t['slug']}"
    return False, None

def main():
    with open(TOOLS_JSON_PATH, 'r', encoding='utf-8') as f:
        tools = json.load(f)

    existing_slugs = {t["slug"].lower() for t in tools}
    print(f"现有工具: {len(tools)} 个")

    added = 0
    skipped = 0
    for t in NEW_TOOLS:
        dup, reason = is_duplicate(t["name"], tools)
        if dup:
            print(f"  跳过: {t['name']} ({reason})")
            skipped += 1
            continue
        if t["slug"].lower() in existing_slugs:
            print(f"  跳过: {t['name']} (slug {t['slug']} 已存在)")
            skipped += 1
            continue
        tools.append(t)
        existing_slugs.add(t["slug"].lower())
        added += 1
        print(f"  ✅ 添加: {t['name']} ({t['slug']})")

    with open(TOOLS_JSON_PATH, 'w', encoding='utf-8') as f:
        json.dump(tools, f, ensure_ascii=False, indent=4)

    print(f"\n完成: 新增 {added} 个, 跳过 {skipped} 个, 总计 {len(tools)} 个")

if __name__ == "__main__":
    main()
